version: "3"

services:
  jekyll:
    image: jekyll/builder:latest
    #command: bundle install
    command: jekyll serve --watch --force_polling --trace
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll